/**
 * U-CALM Concierge — brand imagery manifest.
 *
 * Wired 2026-04-24. 47 slots across 7 sections (IDs 1–10, 13–49; 11 and
 * 12 intentionally skipped). Each entry points at a real generated jpg
 * under /public/brand/<section>/<filename>. The <BrandImage> component
 * still branches on isPlaceholder(src) so unfilled slots (none today)
 * fall back to a gradient stand-in.
 *
 * Components reference slots via the typed export constants below
 * (PAGE_HEROES, HOME_EDITORIAL, SERVICES_SCENES, ABOUT_SCENES,
 * PERSONA_EDITORIAL, CONTACT_EDITORIAL, SEASONAL_BANK). Never import
 * BRAND_IMAGES directly or hard-code filenames.
 */

export type BrandAspect = "4:5" | "16:9" | "1:1" | "3:4" | "21:9";

export type BrandImage = {
  id: number;
  section: string;
  slotKey: string;
  filename: string;
  title: string;
  aspect: BrandAspect;
  src: string;
  alt: string;
  enabled: boolean;
};

export const BRAND_IMAGES: readonly BrandImage[] = [
  {
    id: 1,
    section: "01-brand-heroes",
    slotKey: "hero-morning-consider-it-done",
    filename: "hero-morning-consider-it-done.jpg",
    title: "Morning, considered",
    aspect: "16:9",
    src: "/brand/01-brand-heroes/hero-morning-consider-it-done.jpg",
    alt: "Panelled London hallway at 07:45 — camel wool coat on a hook, leather holdall below, a shoulder receding at the far end.",
    enabled: true,
  },
  {
    id: 2,
    section: "01-brand-heroes",
    slotKey: "hero-concierge-arranged-threshold",
    filename: "hero-concierge-arranged-threshold.jpg",
    title: "Arranged threshold",
    aspect: "16:9",
    src: "/brand/01-brand-heroes/hero-concierge-arranged-threshold.jpg",
    alt: "A London front door at 08:00 from inside — a charcoal wool cuff reaching for the handle, a grey lurcher sitting quietly at heel.",
    enabled: true,
  },
  {
    id: 3,
    section: "01-brand-heroes",
    slotKey: "hero-serene-teal-door",
    filename: "hero-serene-teal-door.jpg",
    title: "Serene Teal door, Lugano",
    aspect: "4:5",
    src: "/brand/01-brand-heroes/hero-serene-teal-door.jpg",
    alt: "A Serene Teal painted door in pale stone, a Lugano città vecchia lane at 08:30.",
    enabled: true,
  },
  {
    id: 4,
    section: "01-brand-heroes",
    slotKey: "hero-kitchen-prepared",
    filename: "hero-kitchen-prepared.jpg",
    title: "Kitchen, prepared",
    aspect: "4:5",
    src: "/brand/01-brand-heroes/hero-kitchen-prepared.jpg",
    alt: "Walnut kitchen island at 07:15 — a linen-lined tray with coffee and pear, a charcoal wool cuff settling it into place.",
    enabled: true,
  },
  {
    id: 5,
    section: "01-brand-heroes",
    slotKey: "hero-study-lamplit-considered",
    filename: "hero-study-lamplit-considered.jpg",
    title: "Study, lamplit",
    aspect: "4:5",
    src: "/brand/01-brand-heroes/hero-study-lamplit-considered.jpg",
    alt: "Panelled study at 19:00 — a linen-shaded lamp on a walnut desk, a closed hardback, one cream porcelain tumbler.",
    enabled: true,
  },
  {
    id: 6,
    section: "01-brand-heroes",
    slotKey: "hero-villa-terrace-dawn",
    filename: "hero-villa-terrace-dawn.jpg",
    title: "Villa terrace, first light",
    aspect: "21:9",
    src: "/brand/01-brand-heroes/hero-villa-terrace-dawn.jpg",
    alt: "A Ticinese villa terrace above Lake Lugano at 06:45 — mist on water, first pale light on Monte San Salvatore.",
    enabled: true,
  },
  {
    id: 7,
    section: "01-brand-heroes",
    slotKey: "hero-chalet-evening",
    filename: "hero-chalet-evening.jpg",
    title: "Chalet evening, restored",
    aspect: "16:9",
    src: "/brand/01-brand-heroes/hero-chalet-evening.jpg",
    alt: "A Saanen chalet sitting room at 18:45 — low hearth fire, a grey lurcher asleep on the rug.",
    enabled: true,
  },
  {
    id: 8,
    section: "01-brand-heroes",
    slotKey: "hero-mediterranean-villa-dusk",
    filename: "hero-mediterranean-villa-dusk.jpg",
    title: "Mediterranean villa, dusk",
    aspect: "16:9",
    src: "/brand/01-brand-heroes/hero-mediterranean-villa-dusk.jpg",
    alt: "A Cap Ferrat villa terrace at 18:15 — limestone warmed by last champagne light, a pair of cream linen chairs.",
    enabled: true,
  },
  {
    id: 9,
    section: "01-brand-heroes",
    slotKey: "hero-concierge-note",
    filename: "hero-concierge-note.jpg",
    title: "Concierge moment",
    aspect: "1:1",
    src: "/brand/01-brand-heroes/hero-concierge-note.jpg",
    alt: "A cream handwritten note on a walnut console, close-up, unprinted — the concierge's quiet arrangement.",
    enabled: true,
  },
  {
    id: 10,
    section: "01-brand-heroes",
    slotKey: "hero-member-residence-afternoon",
    filename: "hero-member-residence-afternoon.jpg",
    title: "Member residence, afternoon",
    aspect: "4:5",
    src: "/brand/01-brand-heroes/hero-member-residence-afternoon.jpg",
    alt: "A member's residence in late afternoon — warm overcast light on a reading chair, a closed book placed beside it.",
    enabled: true,
  },
  {
    id: 13,
    section: "02-services",
    slotKey: "services-hero-running-house",
    filename: "services-hero-running-house.jpg",
    title: "One door, one concierge",
    aspect: "16:9",
    src: "/brand/02-services/services-hero-running-house.jpg",
    alt: "A single residential door held open — one concierge stepping out with a small folded garment, the member just visible on the threshold.",
    enabled: true,
  },
  {
    id: 14,
    section: "02-services",
    slotKey: "services-phone-quiet-line",
    filename: "services-phone-quiet-line.jpg",
    title: "The quiet line",
    aspect: "4:5",
    src: "/brand/02-services/services-phone-quiet-line.jpg",
    alt: "A landline handset on a walnut desk — warm afternoon light, a small notepad beside, a hand in a charcoal wool cuff mid-write.",
    enabled: true,
  },
  {
    id: 15,
    section: "02-services",
    slotKey: "services-ground-household",
    filename: "services-ground-household.jpg",
    title: "Ground services, midday",
    aspect: "4:5",
    src: "/brand/02-services/services-ground-household.jpg",
    alt: "A front door at midday — fresh groceries and a wrapped package placed, a Bernese-cross dog waiting at the step.",
    enabled: true,
  },
  {
    id: 16,
    section: "02-services",
    slotKey: "services-relocations-first-night",
    filename: "services-relocations-first-night.jpg",
    title: "First night in the new house",
    aspect: "16:9",
    src: "/brand/02-services/services-relocations-first-night.jpg",
    alt: "Unpacking in a half-settled lake-facing apartment — first coffee resting on a carton, a hand steadying the mug.",
    enabled: true,
  },
  {
    id: 17,
    section: "02-services",
    slotKey: "services-corporate-boardroom",
    filename: "services-corporate-boardroom.jpg",
    title: "Corporate floor, prepared",
    aspect: "16:9",
    src: "/brand/02-services/services-corporate-boardroom.jpg",
    alt: "A corporate floor at early morning — architectural cool, one small dark-wool figure crossing the lobby.",
    enabled: true,
  },
  {
    id: 18,
    section: "02-services",
    slotKey: "services-travel-event-table",
    filename: "services-travel-event-table.jpg",
    title: "Table prepared",
    aspect: "21:9",
    src: "/brand/02-services/services-travel-event-table.jpg",
    alt: "An outdoor event table laid for two — unlabelled carafe, folded cotton napkins, a waiter's cuff setting the last glass.",
    enabled: true,
  },
  {
    id: 19,
    section: "02-services",
    slotKey: "services-aviation-handoff",
    filename: "services-aviation-handoff.jpg",
    title: "Aviation, handed off",
    aspect: "16:9",
    src: "/brand/02-services/services-aviation-handoff.jpg",
    alt: "Aviation handoff on an apron at dusk — a driver closing a member's car door, discreet.",
    enabled: true,
  },
  {
    id: 20,
    section: "02-services",
    slotKey: "services-cool-calm-preview",
    filename: "services-cool-calm-preview.jpg",
    title: "Cool CALM, preview",
    aspect: "4:5",
    src: "/brand/02-services/services-cool-calm-preview.jpg",
    alt: "Alpine blue hour — ski boots drying on a wooden rack, a hot cup held in a gloved hand.",
    enabled: true,
  },
  {
    id: 21,
    section: "03-cool-calm",
    slotKey: "cool-calm-hero-new-generation",
    filename: "cool-calm-hero-new-generation.jpg",
    title: "Cool CALM, morning-after",
    aspect: "21:9",
    src: "/brand/03-cool-calm/cool-calm-hero-new-generation.jpg",
    alt: "Valle Verzasca cold stone at blue hour, soft mist over the pale river — Cool CALM page hero.",
    enabled: true,
  },
  {
    id: 22,
    section: "04-about",
    slotKey: "about-hero-founding-view",
    filename: "about-hero-founding-view.jpg",
    title: "Lugano, where it began",
    aspect: "21:9",
    src: "/brand/04-about/about-hero-founding-view.jpg",
    alt: "Lake Lugano from Paradiso at dusk, Monte Brè silhouetted — the home where the house began.",
    enabled: true,
  },
  {
    id: 23,
    section: "04-about",
    slotKey: "about-parco-ciani-morning",
    filename: "about-parco-ciani-morning.jpg",
    title: "Parco Ciani, 07:45",
    aspect: "16:9",
    src: "/brand/04-about/about-parco-ciani-morning.jpg",
    alt: "Parco Ciani lakefront at sunrise, a single empty bench on the flagstone path.",
    enabled: true,
  },
  {
    id: 24,
    section: "04-about",
    slotKey: "about-founding-room-2013",
    filename: "about-founding-room-2013.jpg",
    title: "Where the first number was answered",
    aspect: "4:5",
    src: "/brand/04-about/about-founding-room-2013.jpg",
    alt: "A vintage Lugano café interior — two cups on a table, two chairs pulled back, no faces.",
    enabled: true,
  },
  {
    id: 25,
    section: "04-about",
    slotKey: "about-calm-acronym-table",
    filename: "about-calm-acronym-table.jpg",
    title: "Concierge and Lifestyle Management",
    aspect: "1:1",
    src: "/brand/04-about/about-calm-acronym-table.jpg",
    alt: "A cream card on walnut with four quiet tonal shapes arranged — C, A, L, M abstracted, no literal text.",
    enabled: true,
  },
  {
    id: 26,
    section: "04-about",
    slotKey: "about-household-linen-press",
    filename: "about-household-linen-press.jpg",
    title: "House, prepared",
    aspect: "4:5",
    src: "/brand/04-about/about-household-linen-press.jpg",
    alt: "A Ticinese household linen press — stacked folded towels, a warm domestic still life.",
    enabled: true,
  },
  {
    id: 27,
    section: "04-about",
    slotKey: "about-team-threshold",
    filename: "about-team-threshold.jpg",
    title: "The team, in passing",
    aspect: "16:9",
    src: "/brand/04-about/about-team-threshold.jpg",
    alt: "A small Lugano office — three figures at work in quiet profile, all out of focus, back-view.",
    enabled: true,
  },
  {
    id: 28,
    section: "05-personas",
    slotKey: "persona-expat-hero",
    filename: "persona-expat-hero.jpg",
    title: "Sarah — settled, not yet home",
    aspect: "16:9",
    src: "/brand/05-personas/persona-expat-hero.jpg",
    alt: "Sarah, the Expat — a quiet Paradiso neighbourhood, a child's shoes by the door, no child in frame.",
    enabled: true,
  },
  {
    id: 29,
    section: "05-personas",
    slotKey: "persona-expat-editorial",
    filename: "persona-expat-editorial.jpg",
    title: "Thursday, school-run kerb",
    aspect: "4:5",
    src: "/brand/05-personas/persona-expat-editorial.jpg",
    alt: "Thursday morning at the school-run kerb — a parked estate car, a blank bilingual notice on the console inside.",
    enabled: true,
  },
  {
    id: 30,
    section: "05-personas",
    slotKey: "persona-ticinese-hero",
    filename: "persona-ticinese-hero.jpg",
    title: "Giovanni — the family villa, afternoon",
    aspect: "21:9",
    src: "/brand/05-personas/persona-ticinese-hero.jpg",
    alt: "Giovanni, the Ticinese — the family villa terrace in summer afternoon, multi-generational depth.",
    enabled: true,
  },
  {
    id: 31,
    section: "05-personas",
    slotKey: "persona-ticinese-editorial",
    filename: "persona-ticinese-editorial.jpg",
    title: "Sunday, Gandria kitchen",
    aspect: "4:5",
    src: "/brand/05-personas/persona-ticinese-editorial.jpg",
    alt: "Sunday in a Gandria kitchen — a grandfather's glasses resting on a cookbook, a cat on the sill.",
    enabled: true,
  },
  {
    id: 32,
    section: "05-personas",
    slotKey: "persona-corporate-hero",
    filename: "persona-corporate-hero.jpg",
    title: "Corporate HR — the executive arrival",
    aspect: "16:9",
    src: "/brand/05-personas/persona-corporate-hero.jpg",
    alt: "Corporate HR — the Lugano finance district at 07:00, architectural cool, a single dark-wool figure crossing.",
    enabled: true,
  },
  {
    id: 33,
    section: "05-personas",
    slotKey: "persona-corporate-editorial",
    filename: "persona-corporate-editorial.jpg",
    title: "Boardroom, off-site handed",
    aspect: "4:5",
    src: "/brand/05-personas/persona-corporate-editorial.jpg",
    alt: "A Lugano office boardroom prepared — one leather holdall at the chair's foot, off-site handed.",
    enabled: true,
  },
  {
    id: 34,
    section: "05-personas",
    slotKey: "persona-visitor-hero",
    filename: "persona-visitor-hero.jpg",
    title: "Visitor — the lake table, afternoon",
    aspect: "16:9",
    src: "/brand/05-personas/persona-visitor-hero.jpg",
    alt: "The Visitor — a lake-facing hotel table in the afternoon, one chair pulled out, unstaged.",
    enabled: true,
  },
  {
    id: 35,
    section: "05-personas",
    slotKey: "persona-visitor-editorial",
    filename: "persona-visitor-editorial.jpg",
    title: "Visitor — the suite, settled",
    aspect: "4:5",
    src: "/brand/05-personas/persona-visitor-editorial.jpg",
    alt: "The Visitor's suite, settled — a leather suitcase opened, folded linen inside, the room at rest.",
    enabled: true,
  },
  {
    id: 36,
    section: "06-contact",
    slotKey: "contact-hero-threshold",
    filename: "contact-hero-threshold.jpg",
    title: "One door, one conversation",
    aspect: "21:9",
    src: "/brand/06-contact/contact-hero-threshold.jpg",
    alt: "A cream blank note on linen beside a porcelain cup of tea — one conversation, the quietest frame.",
    enabled: true,
  },
  {
    id: 37,
    section: "06-contact",
    slotKey: "contact-editorial-notebook",
    filename: "contact-editorial-notebook.jpg",
    title: "First conversation, quietly",
    aspect: "4:5",
    src: "/brand/06-contact/contact-editorial-notebook.jpg",
    alt: "A blank leather notebook opened on a desk, a pen lying beside — the first conversation, quietly.",
    enabled: true,
  },
  {
    id: 38,
    section: "07-seasonal",
    slotKey: "seasonal-spring-magnolia-threshold",
    filename: "seasonal-spring-magnolia-threshold.jpg",
    title: "Spring threshold, magnolia",
    aspect: "16:9",
    src: "/brand/07-seasonal/seasonal-spring-magnolia-threshold.jpg",
    alt: "A Lugano townhouse door in mid-March — a single pale magnolia bud on a bare branch beside a Serene Teal threshold.",
    enabled: true,
  },
  {
    id: 39,
    section: "07-seasonal",
    slotKey: "seasonal-summer-lake-blue-hour",
    filename: "seasonal-summer-lake-blue-hour.jpg",
    title: "Summer, lake at blue hour",
    aspect: "21:9",
    src: "/brand/07-seasonal/seasonal-summer-lake-blue-hour.jpg",
    alt: "Lake Lugano from a Paradiso terrace at blue hour in July — a teak chair, a cream linen throw folded on its arm.",
    enabled: true,
  },
  {
    id: 40,
    section: "07-seasonal",
    slotKey: "seasonal-autumn-cat-chair",
    filename: "seasonal-autumn-cat-chair.jpg",
    title: "Autumn, cat on the reading chair",
    aspect: "4:5",
    src: "/brand/07-seasonal/seasonal-autumn-cat-chair.jpg",
    alt: "A walnut reading room in late October — amber light on a deep-teal chair, a grey tabby cat asleep on the throw.",
    enabled: true,
  },
  {
    id: 41,
    section: "07-seasonal",
    slotKey: "seasonal-winter-hearth-warmth",
    filename: "seasonal-winter-hearth-warmth.jpg",
    title: "Winter, hearth and lurcher",
    aspect: "16:9",
    src: "/brand/07-seasonal/seasonal-winter-hearth-warmth.jpg",
    alt: "A Saanen chalet at 17:15 in January — hearth fire, a grey lurcher stretched along the rug, snow beyond the window.",
    enabled: true,
  },
  {
    id: 42,
    section: "07-seasonal",
    slotKey: "seasonal-christmas-table-quiet",
    filename: "seasonal-christmas-table-quiet.jpg",
    title: "Christmas, table laid quietly",
    aspect: "4:5",
    src: "/brand/07-seasonal/seasonal-christmas-table-quiet.jpg",
    alt: "A Ticinese dining table set for four on Christmas Eve — pine and dried hydrangea, blank cream card at the nearest place.",
    enabled: true,
  },
  {
    id: 43,
    section: "07-seasonal",
    slotKey: "seasonal-new-year-first-light",
    filename: "seasonal-new-year-first-light.jpg",
    title: "New Year, first light",
    aspect: "16:9",
    src: "/brand/07-seasonal/seasonal-new-year-first-light.jpg",
    alt: "Parco Ciani lakefront at 07:45 on 1 January — Monte Brè in first pale light, a cream cashmere scarf folded on a bench.",
    enabled: true,
  },
  {
    id: 44,
    section: "07-seasonal",
    slotKey: "seasonal-back-to-school-shoes",
    filename: "seasonal-back-to-school-shoes.jpg",
    title: "Back to school, quiet hall",
    aspect: "4:5",
    src: "/brand/07-seasonal/seasonal-back-to-school-shoes.jpg",
    alt: "A Paradiso apartment entry hall on a September Monday — a small pair of polished school shoes, a blank notice on the console.",
    enabled: true,
  },
  {
    id: 45,
    section: "07-seasonal",
    slotKey: "seasonal-midsummer-terrace-laid",
    filename: "seasonal-midsummer-terrace-laid.jpg",
    title: "Midsummer, terrace laid",
    aspect: "16:9",
    src: "/brand/07-seasonal/seasonal-midsummer-terrace-laid.jpg",
    alt: "A Ticinese stone terrace at 19:30 in late July — an outdoor table laid for two, two chairs pulled out, the guests at the railing.",
    enabled: true,
  },
  {
    id: 46,
    section: "07-seasonal",
    slotKey: "seasonal-autumn-lurcher-walk",
    filename: "seasonal-autumn-lurcher-walk.jpg",
    title: "Autumn, lurcher on the lane",
    aspect: "4:5",
    src: "/brand/07-seasonal/seasonal-autumn-lurcher-walk.jpg",
    alt: "A cobbled Gandria lane on a clear October morning — a grey lurcher walking a step ahead of a charcoal wool cuff, no face in frame.",
    enabled: true,
  },
  {
    id: 47,
    section: "07-seasonal",
    slotKey: "seasonal-disruption-umbrella-held",
    filename: "seasonal-disruption-umbrella-held.jpg",
    title: "Disruption, the arrangement held",
    aspect: "16:9",
    src: "/brand/07-seasonal/seasonal-disruption-umbrella-held.jpg",
    alt: "A Lugano portico in sudden rain — a dark teak umbrella held over a cream package on a dry bench, the arrangement held.",
    enabled: true,
  },
  {
    id: 48,
    section: "07-seasonal",
    slotKey: "seasonal-spring-dinner-laid",
    filename: "seasonal-spring-dinner-laid.jpg",
    title: "Spring, dinner laid",
    aspect: "4:5",
    src: "/brand/07-seasonal/seasonal-spring-dinner-laid.jpg",
    alt: "A walnut dining table in a Lugano apartment in late April — set for three, a cat on the window sill watching the street.",
    enabled: true,
  },
  {
    id: 49,
    section: "07-seasonal",
    slotKey: "seasonal-returning-home-threshold",
    filename: "seasonal-returning-home-threshold.jpg",
    title: "Returning home, shoulders settle",
    aspect: "16:9",
    src: "/brand/07-seasonal/seasonal-returning-home-threshold.jpg",
    alt: "A Paradiso apartment threshold at 18:30 in early November — a woman just stepping inside, a grey lurcher rising to greet her.",
    enabled: true,
  },
];

/** Stable keys components import — never reference raw ids. */
export const PAGE_HEROES = {
  home:      1,
  services: 13,
  coolCalm: 21,
  about:    22,
  expat:    28,
  ticinese: 30,
  corporate: 32,
  visitor:  34,
  contact:  36,
} as const;

export const HOME_EDITORIAL = {
  one: 5,
  two: 8,
} as const;

export const SERVICES_SCENES = {
  phone:        14,
  ground:       15,
  relocations:  16,
  corporate:    17,
  travelEvents: 18,
  aviation:     19,
  coolCalm:     20,
} as const;

export const ABOUT_SCENES = {
  parcoCiani:   23,
  founding2013: 24,
  calmAcronym:  25,
  household:    26,
  team:         27,
} as const;

export const PERSONA_EDITORIAL = {
  expat:     29,
  ticinese:  31,
  corporate: 33,
  visitor:   35,
} as const;

export const CONTACT_EDITORIAL = {
  one: 37,
} as const;

export const SEASONAL_BANK = {
  springMagnolia:     38,
  summerBlueHour:     39,
  autumnCatChair:     40,
  winterHearth:       41,
  christmasTable:     42,
  newYearFirstLight:  43,
  backToSchool:       44,
  midsummerTerrace:   45,
  autumnLurcherWalk:  46,
  disruption:         47,
  springDinner:       48,
  returningHome:      49,
} as const;

export function byId(id: number): BrandImage {
  const image = BRAND_IMAGES.find((entry) => entry.id === id);
  if (!image) {
    throw new Error(`No brand image found with id ${id}. Check src/brand/imagery.ts.`);
  }
  return image;
}

export function bySection(section: string): readonly BrandImage[] {
  return BRAND_IMAGES.filter((entry) => entry.section === section);
}

/** True once Stage 2 has filled a real path in. */
export function isPlaceholder(image: BrandImage): boolean {
  return image.src.startsWith("TODO:");
}
